name: StandardRB

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
    strategy:
      fail-fast: true
      matrix:
        ruby-version:
          - "3.4"
    steps:
      - name: Run StandardRB
        uses: standardrb/standard-ruby-action@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          autofix: false
