name: StandardRB

on:
  push:
    # branches: [main]
  pull_request:
    types: [opened, reopened]
    # branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby 3.2
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.0
          bundler-cache: true
      - name: Install gems
        run: |
          bundle config path vendor/bundle
          bundle check || (bundle install --jobs=4 --retry=3 && bundle clean)
      - name: Run StandardRB
        run: |
          bundle exec standardrb
