name: StandardRB

on:
  push:
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby 3.2
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.0
      - name: Cache gems
        uses: actions/cache@v3
        with:
          path: gemfiles/vendor/bundle
          key: ${{ runner.os }}-rubocop-${{ hashFiles('Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-rubocop-
      - name: Install gems
        run: |
          bundle config path vendor/bundle
          bundle check || (bundle install --jobs=4 --retry=3 && bundle clean)
      - name: Run StandardRB
        run: |
          bundle exec standardrb
